defmodule SAndP500 do
  def companies do
    [
      {"A", "Agilent Technologies"},
      {"AAL", "American Airlines Group"},
      {"AAP", "Advance Auto Parts"},
      {"AAPL", "Apple"},
      {"ABBV", "AbbVie"},
      {"ABC", "AmerisourceBergen"},
      {"ABMD", "Abiomed"},
      {"ABT", "Abbott Laboratories"},
      {"ACN", "Accenture"},
      {"ADBE", "Adobe"},
      {"ADI", "Analog Devices"},
      {"ADM", "Archer-Daniels Midland"},
      {"ADP", "Automatic Data Processing"},
      {"ADSK", "Autodesk"},
      {"AEE", "Ameren"},
      {"AEP", "American Electric Power"},
      {"AES", "AES"},
      {"AFL", "Aflac"},
      {"AIG", "American Intl Gr"},
      {"AIZ", "Assurant"},
      {"AJG", "Arthur J. Gallagher"},
      {"AKAM", "Akamai Technologies"},
      {"ALB", "Albemarle"},
      {"ALGN", "Align Tech"},
      {"ALK", "Alaska Air Group"},
      {"ALL", "Allstate"},
      {"ALLE", "Allegion"},
      {"ALXN", "Alexion Pharmaceuticals"},
      {"AMAT", "Applied Materials"},
      {"AMCR", "Amcor"},
      {"AMD", "Advanced Micro Devices"},
      {"AME", "AMETEK"},
      {"AMGN", "Amgen"},
      {"AMP", "Ameriprise Financial"},
      {"AMT", "American Tower"},
      {"AMZN", "Amazon.com"},
      {"ANET", "Arista Networks"},
      {"ANSS", "Ansys"},
      {"ANTM", "Anthem"},
      {"AON", "Aon"},
      {"AOS", "A.O. Smith"},
      {"APA", "Apache"},
      {"APD", "Air Products & Chemicals"},
      {"APH", "Amphenol"},
      {"APTV", "Aptiv"},
      {"ARE", "Alexandria Real Estate"},
      {"ATO", "Atmos Energy"},
      {"ATVI", "Activision Blizzard"},
      {"AVB", "AvalonBay Communities"},
      {"AVGO", "Broadcom"},
      {"AVY", "Avery Dennison"},
      {"AWK", "American Water Works Co"},
      {"AXP", "American Express"},
      {"AZO", "AutoZone"},
      {"BA", "Boeing"},
      {"BAC", "Bank of America"},
      {"BAX", "Baxter International"},
      {"BBY", "Best Buy Co"},
      {"BDX", "Becton, Dickinson"},
      {"BEN", "Franklin Resources"},
      {"BF.B", "Brown-Forman"},
      {"BIIB", "Biogen"},
      {"BIO", "Bio-Rad Laboratories"},
      {"BK", "Bank of New York Mellon"},
      {"BKNG", "Booking Holdings"},
      {"BKR", "Baker Hughes"},
      {"BLK", "BlackRock"},
      {"BLL", "Ball"},
      {"BMY", "Bristol-Myers Squibb"},
      {"BR", "Broadridge Financial Soln"},
      {"BRK.B", "Berkshire Hathaway"},
      {"BSX", "Boston Scientific"},
      {"BWA", "BorgWarner"},
      {"BXP", "Boston Properties"},
      {"C", "Citigroup"},
      {"CAG", "Conagra Brands"},
      {"CAH", "Cardinal Health"},
      {"CARR", "Carrier Global"},
      {"CAT", "Caterpillar"},
      {"CB", "Chubb"},
      {"CBRE", "CBRE Group"},
      {"CCI", "Crown Castle Intl"},
      {"CCL", "Carnival"},
      {"CDNS", "Cadence Design Systems"},
      {"CDW", "CDW"},
      {"CE", "Celanese"},
      {"CERN", "Cerner"},
      {"CF", "CF Industries Holdings"},
      {"CFG", "Citizens Financial Group"},
      {"CHD", "Church & Dwight Co"},
      {"CHRW", "C.H. Robinson Worldwide"},
      {"CHTR", "Charter Communications"},
      {"CI", "Cigna"},
      {"CINF", "Cincinnati Financial"},
      {"CL", "Colgate-Palmolive"},
      {"CLX", "Clorox"},
      {"CMA", "Comerica"},
      {"CMCSA", "Comcast"},
      {"CME", "CME Group"},
      {"CMG", "Chipotle Mexican Grill"},
      {"CMI", "Cummins"},
      {"CMS", "CMS Energy"},
      {"CNC", "Centene"},
      {"CNP", "CenterPoint Energy"},
      {"COF", "Capital One Financial"},
      {"COG", "Cabot Oil & Gas"},
      {"COO", "Cooper Companies"},
      {"COP", "ConocoPhillips"},
      {"COST", "Costco Wholesale"},
      {"CPB", "Campbell Soup"},
      {"CPRT", "Copart"},
      {"CRM", "Salesforce.com"},
      {"CSCO", "Cisco Systems"},
      {"CSX", "CSX"},
      {"CTAS", "Cintas"},
      {"CTLT", "Catalent"},
      {"CTSH", "Cognizant Tech Solns"},
      {"CTVA", "Corteva"},
      {"CTXS", "Citrix Systems"},
      {"CVS", "CVS Health"},
      {"CVX", "Chevron"},
      {"D", "Dominion Energy"},
      {"DAL", "Delta Air Lines"},
      {"DD", "DuPont de Nemours"},
      {"DE", "Deere"},
      {"DFS", "Discover Financial"},
      {"DG", "Dollar General"},
      {"DGX", "Quest Diagnostics"},
      {"DHI", "D.R. Horton"},
      {"DHR", "Danaher"},
      {"DIS", "Walt Disney"},
      {"DISCA", "Discovery"},
      {"DISCK", "Discovery"},
      {"DISH", "DISH Network"},
      {"DLR", "Digital Realty Trust"},
      {"DLTR", "Dollar Tree"},
      {"DOV", "Dover"},
      {"DOW", "Dow"},
      {"DPZ", "Domino’s Pizza"},
      {"DRE", "Duke Realty"},
      {"DRI", "Darden Restaurants"},
      {"DTE", "DTE Energy"},
      {"DUK", "Duke Energy"},
      {"DVA", "DaVita"},
      {"DVN", "Devon Energy"},
      {"DXC", "DXC Technology"},
      {"DXCM", "DexCom"},
      {"EA", "Electronic Arts"},
      {"EBAY", "eBay"},
      {"ECL", "Ecolab"},
      {"ED", "Consolidated Edison"},
      {"EFX", "Equifax"},
      {"EIX", "Edison Intl"},
      {"EL", "Estee Lauder Cos"},
      {"EMN", "Eastman Chemical"},
      {"EMR", "Emerson Electric"},
      {"ENPH", "Enphase Energy"},
      {"EOG", "EOG Resources"},
      {"EQIX", "Equinix"},
      {"EQR", "Equity Residential"},
      {"ES", "Eversource Energy"},
      {"ESS", "Essex Property Trust"},
      {"ETN", "Eaton Corp"},
      {"ETR", "Entergy"},
      {"ETSY", "Etsy"},
      {"EVRG", "Evergy"},
      {"EW", "Edwards Lifesciences"},
      {"EXC", "Exelon"},
      {"EXPD", "Expeditors International"},
      {"EXPE", "Expedia Group"},
      {"EXR", "Extra Space Storage"},
      {"F", "Ford Motor"},
      {"FANG", "Diamondback Energy"},
      {"FAST", "Fastenal"},
      {"FB", "Facebook"},
      {"FBHS", "Fortune Brands Home"},
      {"FCX", "Freeport-McMoRan"},
      {"FDX", "FedEx"},
      {"FE", "FirstEnergy"},
      {"FFIV", "F5 Networks"},
      {"FIS", "Fidelity National Info"},
      {"FISV", "Fiserv"},
      {"FITB", "Fifth Third Bancorp"},
      {"FLIR", "FLIR Systems"},
      {"FLS", "Flowserve"},
      {"FLT", "Fleetcor Technologies"},
      {"FMC", "FMC"},
      {"FOX", "Fox"},
      {"FOXA", "Fox"},
      {"FRC", "First Republic Bank"},
      {"FRT", "Federal Realty Investment"},
      {"FTNT", "Fortinet"},
      {"FTV", "Fortive"},
      {"GD", "General Dynamics"},
      {"GE", "General Electric"},
      {"GILD", "Gilead Sciences"},
      {"GIS", "General Mills"},
      {"GL", "Globe Life"},
      {"GLW", "Corning"},
      {"GM", "General Motors"},
      {"GOOG", "Alphabet"},
      {"GOOGL", "Alphabet"},
      {"GPC", "Genuine Parts"},
      {"GPN", "Global Payments"},
      {"GPS", "Gap"},
      {"GRMN", "Garmin"},
      {"GS", "Goldman Sachs Group"},
      {"GWW", "W.W. Grainger"},
      {"HAL", "Halliburton"},
      {"HAS", "Hasbro"},
      {"HBAN", "Huntington Bancshares"},
      {"HBI", "Hanesbrands"},
      {"HCA", "HCA Healthcare"},
      {"HD", "Home Depot"},
      {"HES", "Hess"},
      {"HFC", "HollyFrontier"},
      {"HIG", "Hartford Finl Servs Gr"},
      {"HII", "Huntington Ingalls Indus"},
      {"HLT", "Hilton Worldwide Holdings"},
      {"HOLX", "Hologic"},
      {"HON", "Honeywell International"},
      {"HPE", "Hewlett Packard"},
      {"HPQ", "HP"},
      {"HRL", "Hormel Foods"},
      {"HSIC", "Henry Schein"},
      {"HST", "Host Hotels & Resorts"},
      {"HSY", "Hershey"},
      {"HUM", "Humana"},
      {"HWM", "Howmet Aerospace"},
      {"IBM", "IBM"},
      {"ICE", "Intercontinental Exchange"},
      {"IDXX", "IDEXX Laboratories"},
      {"IEX", "IDEX"},
      {"IFF", "Intl Flavors & Fragrances"},
      {"ILMN", "Illumina"},
      {"INCY", "Incyte"},
      {"INFO", "IHS Markit"},
      {"INTC", "Intel"},
      {"INTU", "Intuit"},
      {"IP", "International Paper"},
      {"IPG", "Interpublic Gr of Cos"},
      {"IPGP", "IPG Photonics"},
      {"IQV", "IQVIA Holdings"},
      {"IR", "Ingersoll Rand"},
      {"IRM", "Iron Mountain"},
      {"ISRG", "Intuitive Surgical"},
      {"IT", "Gartner"},
      {"ITW", "Illinois Tool Works"},
      {"IVZ", "Invesco"},
      {"J", "Jacobs Engineering Group"},
      {"JBHT", "JB Hunt Transport Servs"},
      {"JCI", "Johnson Controls Intl"},
      {"JKHY", "Jack Henry & Associates"},
      {"JNJ", "Johnson & Johnson"},
      {"JNPR", "Juniper Networks"},
      {"JPM", "JPMorgan Chase"},
      {"K", "Kellogg"},
      {"KEY", "KeyCorp"},
      {"KEYS", "Keysight Technologies"},
      {"KHC", "Kraft Heinz"},
      {"KIM", "Kimco Realty"},
      {"KLAC", "KLA"},
      {"KMB", "Kimberly-Clark"},
      {"KMI", "Kinder Morgan"},
      {"KMX", "CarMax"},
      {"KO", "Coca-Cola"},
      {"KR", "Kroger"},
      {"KSU", "Kansas City Southern"},
      {"L", "Loews"},
      {"LB", "L Brands"},
      {"LDOS", "Leidos Holdings"},
      {"LEG", "Leggett & Platt"},
      {"LEN", "Lennar"},
      {"LH", "Laboratory Corp"},
      {"LHX", "L3Harris Technologies"},
      {"LIN", "Linde"},
      {"LKQ", "LKQ"},
      {"LLY", "Eli Lilly"},
      {"LMT", "Lockheed Martin"},
      {"LNC", "Lincoln National"},
      {"LNT", "Alliant Energy"},
      {"LOW", "Lowe’s Companies"},
      {"LRCX", "Lam Research"},
      {"LUMN", "Lumen Technologies"},
      {"LUV", "Southwest Airlines"},
      {"LVS", "Las Vegas Sands"},
      {"LW", "Lamb Weston Hldgs"},
      {"LYB", "LyondellBasell Industries"},
      {"LYV", "Live Nation Entertainment"},
      {"MA", "Mastercard"},
      {"MAA", "Mid-America Apartment"},
      {"MAR", "Marriott Intl"},
      {"MAS", "Masco"},
      {"MCD", "McDonald’s"},
      {"MCHP", "Microchip Technology"},
      {"MCK", "McKesson"},
      {"MCO", "Moody’s"},
      {"MDLZ", "Mondelez International"},
      {"MDT", "Medtronic"},
      {"MET", "MetLife"},
      {"MGM", "MGM Resorts Intl"},
      {"MHK", "Mohawk Industries"},
      {"MKC", "McCormick & Co"},
      {"MKTX", "MarketAxess Holdings"},
      {"MLM", "Martin Marietta Materials"},
      {"MMC", "Marsh & McLennan"},
      {"MMM", "3M"},
      {"MNST", "Monster Beverage"},
      {"MO", "Altria Group"},
      {"MOS", "Mosaic"},
      {"MPC", "Marathon Petroleum"},
      {"MPWR", "Monolithic Power Systems"},
      {"MRK", "Merck & Co"},
      {"MRO", "Marathon Oil"},
      {"MS", "Morgan Stanley"},
      {"MSCI", "MSCI"},
      {"MSFT", "Microsoft"},
      {"MSI", "Motorola Solutions"},
      {"MTB", "M&T Bank"},
      {"MTD", "Mettler-Toledo Intl"},
      {"MU", "Micron Technology"},
      {"MXIM", "Maxim Integrated Products"},
      {"NCLH", "Norwegian Cruise Line"},
      {"NDAQ", "Nasdaq"},
      {"NEE", "NextEra Energy"},
      {"NEM", "Newmont"},
      {"NFLX", "Netflix"},
      {"NI", "NiSource"},
      {"NKE", "Nike"},
      {"NLOK", "NortonLifeLock"},
      {"NLSN", "Nielsen Holdings"},
      {"NOC", "Northrop Grumman"},
      {"NOV", "NOV"},
      {"NOW", "ServiceNow"},
      {"NRG", "NRG Energy"},
      {"NSC", "Norfolk Southern"},
      {"NTAP", "NetApp"},
      {"NTRS", "Northern Trust"},
      {"NUE", "Nucor"},
      {"NVDA", "NVIDIA"},
      {"NVR", "NVR"},
      {"NWL", "Newell Brands"},
      {"NWS", "News"},
      {"NWSA", "News"},
      {"O", "Realty Income"},
      {"ODFL", "Old Dominion Freight Line"},
      {"OKE", "ONEOK"},
      {"OMC", "Omnicom Group"},
      {"ORCL", "Oracle"},
      {"ORLY", "O’Reilly Automotive"},
      {"OTIS", "Otis Worldwide"},
      {"OXY", "Occidental Petroleum"},
      {"PAYC", "Paycom Software"},
      {"PAYX", "Paychex"},
      {"PBCT", "People’s United Finl"},
      {"PCAR", "PACCAR"},
      {"PEAK", "Healthpeak Properties"},
      {"PEG", "Public Service Enterprise"},
      {"PEP", "PepsiCo"},
      {"PFE", "Pfizer"},
      {"PFG", "Principal Financial Group"},
      {"PG", "Procter & Gamble"},
      {"PGR", "Progressive"},
      {"PH", "Parker Hannifin"},
      {"PHM", "PulteGroup"},
      {"PKG", "Packaging Corp of America"},
      {"PKI", "PerkinElmer"},
      {"PLD", "Prologis"},
      {"PM", "Philip Morris Intl"},
      {"PNC", "PNC Financial Services Gr"},
      {"PNR", "Pentair"},
      {"PNW", "Pinnacle West Capital"},
      {"POOL", "Pool"},
      {"PPG", "PPG Industries"},
      {"PPL", "PPL"},
      {"PRGO", "Perrigo"},
      {"PRU", "Prudential Financial"},
      {"PSA", "Public Storage"},
      {"PSX", "Phillips 66"},
      {"PVH", "PVH"},
      {"PWR", "Quanta Services"},
      {"PXD", "Pioneer Natural Resources"},
      {"PYPL", "PayPal Holdings"},
      {"QCOM", "Qualcomm"},
      {"QRVO", "Qorvo"},
      {"RCL", "Royal Caribbean Group"},
      {"RE", "Everest Re Group"},
      {"REG", "Regency Centers"},
      {"REGN", "Regeneron Pharmaceuticals"},
      {"RF", "Regions Financial"},
      {"RHI", "Robert Half International"},
      {"RJF", "Raymond James Financial"},
      {"RL", "Ralph Lauren"},
      {"RMD", "ResMed"},
      {"ROK", "Rockwell Automation"},
      {"ROL", "Rollins"},
      {"ROP", "Roper Technologies"},
      {"ROST", "Ross Stores"},
      {"RSG", "Republic Services"},
      {"RTX", "Raytheon Technologies"},
      {"SBAC", "SBA Communications"},
      {"SBUX", "Starbucks"},
      {"SCHW", "Charles Schwab"},
      {"SEE", "Sealed Air"},
      {"SHW", "Sherwin-Williams"},
      {"SIVB", "SVB Financial"},
      {"SJM", "JM Smucker"},
      {"SLB", "Schlumberger"},
      {"SLG", "SL Green Realty"},
      {"SNA", "Snap-on"},
      {"SNPS", "Synopsys"},
      {"SO", "Southern"},
      {"SPG", "Simon Property Group"},
      {"SPGI", "S&P Global"},
      {"SRE", "Sempra Energy"},
      {"STE", "Steris"},
      {"STT", "State Street"},
      {"STX", "Seagate Technology"},
      {"STZ", "Constellation Brands"},
      {"SWK", "Stanley Black & Decker"},
      {"SWKS", "Skyworks Solutions"},
      {"SYF", "Synchrony Finl"},
      {"SYK", "Stryker"},
      {"SYY", "Sysco"},
      {"T", "AT&T"},
      {"TAP", "Molson Coors Beverage"},
      {"TDG", "TransDigm Gr"},
      {"TDY", "Teledyne Technologies"},
      {"TEL", "TE Connectivity"},
      {"TER", "Teradyne"},
      {"TFC", "Truist Financial"},
      {"TFX", "Teleflex"},
      {"TGT", "Target"},
      {"TJX", "TJX Companies"},
      {"TMO", "Thermo Fisher Scientific"},
      {"TMUS", "T-Mobile US"},
      {"TPR", "Tapestry"},
      {"TRMB", "Trimble"},
      {"TROW", "T. Rowe Price Group"},
      {"TRV", "Travelers Companies"},
      {"TSCO", "Tractor Supply"},
      {"TSLA", "Tesla"},
      {"TSN", "Tyson Foods"},
      {"TT", "Trane Technologies"},
      {"TTWO", "Take-Two Interactive"},
      {"TWTR", "Twitter"},
      {"TXN", "Texas Instruments"},
      {"TXT", "Textron"},
      {"TYL", "Tyler Technologies"},
      {"UA", "Under Armour"},
      {"UAA", "Under Armour"},
      {"UAL", "United Airlines Holdings"},
      {"UDR", "UDR"},
      {"UHS", "Universal Health Services"},
      {"ULTA", "Ulta Beauty"},
      {"UNH", "UnitedHealth Group"},
      {"UNM", "Unum"},
      {"UNP", "Union Pacific"},
      {"UPS", "United Parcel Service"},
      {"URI", "United Rentals"},
      {"USB", "U.S. Bancorp"},
      {"V", "Visa"},
      {"VAR", "Varian Medical Systems"},
      {"VFC", "VF"},
      {"VIAC", "ViacomCBS"},
      {"VLO", "Valero Energy"},
      {"VMC", "Vulcan Materials"},
      {"VNO", "Vornado Realty"},
      {"VNT", "Vontier"},
      {"VRSK", "Verisk Analytics"},
      {"VRSN", "VeriSign"},
      {"VRTX", "Vertex Pharmaceuticals"},
      {"VTR", "Ventas"},
      {"VTRS", "Viatris"},
      {"VZ", "Verizon Communications"},
      {"WAB", "Westinghouse Air Brake"},
      {"WAT", "Waters"},
      {"WBA", "Walgreens Boots Alliance"},
      {"WDC", "Western Digital"},
      {"WEC", "WEC Energy Gr"},
      {"WELL", "Welltower"},
      {"WFC", "Wells Fargo"},
      {"WHR", "Whirlpool"},
      {"WLTW", "Willis Towers Watson"},
      {"WM", "Waste Management"},
      {"WMB", "Williams Companies"},
      {"WMT", "Walmart"},
      {"WRB", "WR Berkley"},
      {"WRK", "WestRock"},
      {"WST", "West Pharmaceutical Servs"},
      {"WU", "The Western Union"},
      {"WY", "Weyerhaeuser"},
      {"WYNN", "Wynn Resorts"},
      {"XEL", "Xcel Energy"},
      {"XLNX", "Xilinx"},
      {"XOM", "Exxon Mobil"},
      {"XRAY", "Dentsply Sirona"},
      {"XRX", "Xerox Holdings"},
      {"XYL", "Xylem"},
      {"YUM", "Yum Brands"},
      {"ZBH", "Zimmer Biomet Holdings"},
      {"ZBRA", "Zebra Technologies"},
      {"ZION", "Zions Bancorp"},
      {"ZTS", "Zoetis"}
    ]
  end
end
